name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_macos:
    runs-on: macos-12-xl

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: exam-customizer-mac.app
        path: target/release/exam-customizer.app

  build_linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: exam-customizer-linux
        path: target/release/exam-customizer

  build_windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: exam-customizer-windows
        path: target/release/exam-customizer.exe
